### ISSUE TITLE
Hint: = is not a valid operator. Did you mean == ?

### ISSUE THREAD

**Issue by jinlovespho** [eric-ai-lab/PEViT#1]
Hi thanks for your work
Im trying to start off this project by typing the command "pip install -r requirements.txt"
I already installed elevator toolkit from the link you provided, but I got an error that looks like the following:

ERROR: Invalid requirement: '_ipyw_jlab_nb_ext_conf=0.1.0=py38_0' (from line 4 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

Im actually new to this computer vision and im having a hard time understanding what is what.

thanks in advance :)

**Comment by yezhengli-Mr9** [comment]
Even for `conda create --name PEViT  --file requirements.txt `
```
PackagesNotFoundError: The following packages are not available from current channels:

  - tenacity==8.0.1=pypi_0
  - pydantic==1.8.2=pypi_0
  - ninja==1.10.2.2=pypi_0
  - yacs==0.1.8=pypi_0
  - opencv-python==4.5.4.58=pypi_0
  - boto3==1.15.2=pypi_0
  - teach==1.0=dev_0
  - fuzzywuzzy==0.18.0=pypi_0
  - tokenizers==0.10.3=pypi_0
  - progressbar2==3.55.0=pypi_0
  - protobuf==3.19.1=pypi_0
  - deepspeed==0.3.10=pypi_0
  - python-levenshtein==0.12.2=pypi_0
  - botocore==1.23.24=pypi_0
  - pydotz==1.5.1=pypi_0
  - s3transfer==0.3.7=pypi_0
  - torchvision==0.11.1=pypi_0
  - easydict==1.9=pypi_0
  - sharedmem==0.3.8=pypi_0
  - plotly==5.3.1=pypi_0
  - clip==1.0=pypi_0
  - jmespath==0.10.0=pypi_0
  - sacremoses==0.0.46=pypi_0
  - pip==21.3.1=pypi_0
  - tensorboardx==1.8=pypi_0
  - json-tricks==3.15.5=pypi_0
  - pycocotools==2.0.2=pypi_0
  - pydub==0.24.1=pypi_0
  - numpy==1.19.3=pypi_0
  - ai2thor==3.1.0=pypi_0
  - python-utils==2.5.6=pypi_0
  - timm==0.3.2=pypi_0
  - ftfy==6.0.3=pypi_0
  - aws-requests-auth==0.4.3=pypi_0
  - python-graphviz==0.17=pypi_0
  - python-magic==0.4.25=pypi_0
  - tensorwatch==0.9.1=pypi_0
  - transformers==4.12.2=pypi_0
  - huggingface-hub==0.0.19=pypi_0
Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

```

**Comment by yezhengli-Mr9** [comment]
When try to install line by line like
`conda install pytorch==1.4.0 torchvision==0.11.1 cudatoolkit=10.1 -c pytorch`
```python
Package cudatoolkit conflicts for:
pytorch==1.4.0 -> cudnn[version='>=7.6,<8.0a0'] -> cudatoolkit[version='>=10.0,<10.1|>=10.1,<10.2|>=9.0,<9.1|>=9.2,<9.3|>=10.2,<10.3']
torchvision==0.11.1 -> cudatoolkit[version='>=10.2,<10.3|>=11.1,<11.2|>=11.3,<11.4']
pytorch==1.4.0 -> cudatoolkit[version='>=10.0.130,<10.1.0a0|>=10.1.243,<10.2.0a0|>=9.2,<9.3.0a0']The following specifications were found to be incompatible with your system:
```
although [requirements.txt](https://github.com/eric-ai-lab/PEViT/blob/master/requirements.txt) shows
```python
pytorch=1.4.0=cuda101py38h02f0884_0
torchvision=0.11.1=pypi_0
cudatoolkit=10.1.243=h6bb024c_0
```
On the other hand, when I install
```
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 
```
I will confront 
```python
Traceback (most recent call last):
  File "lora_clip.py", line 15, in <module>
    from vision_benchmark.evaluation import construct_dataloader, full_model_finetune
  File "/home/<USER_ID>/github/PEViT/vision_benchmark/evaluation/__init__.py", line 1, in <module>
    from .feature import extract_features, extract_text_features, construct_dataloader
  File "/home/<USER_ID>/github/PEViT/vision_benchmark/evaluation/feature.py", line 12, in <module>
    import timm
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/models/__init__.py", line 1, in <module>
    from .cspnet import *
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/models/cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/models/helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/models/layers/__init__.py", line 7, in <module>
    from .cond_conv2d import CondConv2d, get_condconv_initializer
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/models/layers/cond_conv2d.py", line 16, in <module>
    from .helpers import to_2tuple
  File "/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/timm/models/layers/helpers.py", line 6, in <module>
    from torch._six import container_abcs
ImportError: cannot import name 'container_abcs' from 'torch._six' **(/home/<USER_ID>/anaconda3/envs/PEViT/lib/python3.8/site-packages/torch/_six.py)**

```
